<?php
session_start();
include 'db.php';

if (!isset($_SESSION['user_id']) || ($_SESSION['role'] ?? '') !== 'admin') {
    die('Unauthorized access');
}

require_once 'vendor/autoload.php';

use Dompdf\Dompdf;
use Dompdf\Options;

$report_type = $_POST['report_type'] ?? 'all_items';
$status_filter = $_POST['status'] ?? '';
$date_from = $_POST['date_from'] ?? '';
$date_to = $_POST['date_to'] ?? '';
$item_type_filter = $_POST['item_type'] ?? '';

$where = "WHERE 1=1";

if ($report_type === 'lost_items') {
    $where .= " AND lost_items.status = 'lost'";
} elseif ($report_type === 'claimed_items') {
    $where .= " AND lost_items.status IN ('claimed', 'returned')";
}

if ($status_filter) {
    $safe_status = mysqli_real_escape_string($conn, $status_filter);
    $where .= " AND lost_items.status = '$safe_status'";
}

if ($date_from) {
    $safe_from = mysqli_real_escape_string($conn, $date_from);
    $where .= " AND lost_items.date_lost >= '$safe_from'";
}

if ($date_to) {
    $safe_to = mysqli_real_escape_string($conn, $date_to);
    $where .= " AND lost_items.date_lost <= '$safe_to'";
}

if ($item_type_filter) {
    $safe_type = mysqli_real_escape_string($conn, $item_type_filter);
    $where .= " AND lost_items.item_type LIKE '%$safe_type%'";
}

$sql = "SELECT lost_items.*, 
        m1.fullname AS posted_by_name, 
        m2.fullname AS claimer_name
        FROM lost_items
        LEFT JOIN members m1 ON lost_items.user_id = m1.id
        LEFT JOIN members m2 ON lost_items.claimed_by = m2.id
        $where
        ORDER BY lost_items.created_at DESC";

$result = mysqli_query($conn, $sql);
$items = [];
if ($result) {
    while ($row = mysqli_fetch_assoc($result)) {
        $items[] = $row;
    }
}

$count_items = count($items);
$count_lost = 0;
$count_claimed = 0;
foreach ($items as $item) {
    if ($item['status'] === 'lost') $count_lost++;
    if (in_array($item['status'], ['claimed', 'returned'])) $count_claimed++;
}

$html = '
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 3px solid #ffee00;
            padding-bottom: 15px;
        }
        .header h1 {
            color: #616161;
            margin: 0;
            font-size: 24px;
        }
        .header h2 {
            color: #616161;
            margin: 5px 0;
            font-size: 18px;
        }
        .info-box {
            background-color: #f9f9f9;
            padding: 15px;
            margin-bottom: 20px;
            border: 1px solid #ddd;
        }
        .info-box p {
            margin: 5px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        table th {
            background-color: #ffee00;
            color: #616161;
            padding: 10px;
            text-align: left;
            font-weight: bold;
            border: 1px solid #ddd;
        }
        table td {
            padding: 8px;
            border: 1px solid #ddd;
        }
        table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .summary {
            display: flex;
            justify-content: space-around;
            margin: 20px 0;
        }
        .summary-item {
            text-align: center;
            padding: 10px;
        }
        .summary-item strong {
            display: block;
            font-size: 24px;
            color: #616161;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>TIP LOST & FOUND SYSTEM</h1>
        <h2>Items Report</h2>
        <p style="color: #666;">Generated on: ' . date('F d, Y h:i A') . '</p>
    </div>

    <div class="info-box">
        <p><strong>Report Type:</strong> ' . htmlspecialchars(ucwords(str_replace('_', ' ', $report_type))) . '</p>';

if ($status_filter) {
    $html .= '<p><strong>Status Filter:</strong> ' . htmlspecialchars(ucfirst($status_filter)) . '</p>';
}
if ($date_from) {
    $html .= '<p><strong>Date From:</strong> ' . htmlspecialchars($date_from) . '</p>';
}
if ($date_to) {
    $html .= '<p><strong>Date To:</strong> ' . htmlspecialchars($date_to) . '</p>';
}
if ($item_type_filter) {
    $html .= '<p><strong>Item Type:</strong> ' . htmlspecialchars($item_type_filter) . '</p>';
}

$html .= '
        <p><strong>Generated by:</strong> ' . htmlspecialchars($_SESSION['fullname']) . ' (Admin)</p>
    </div>

    <div style="background-color: #ffee00; padding: 15px; margin: 20px 0; border-radius: 5px;">
        <h3 style="margin: 0 0 10px 0; color: #616161;">Summary Statistics</h3>
        <table style="border: none; background: transparent;">
            <tr style="background: transparent;">
                <td style="border: none; font-size: 14px;"><strong>Total Items:</strong></td>
                <td style="border: none; font-size: 14px;">' . $count_items . '</td>
                <td style="border: none; font-size: 14px;"><strong>Currently Lost:</strong></td>
                <td style="border: none; font-size: 14px;">' . $count_lost . '</td>
                <td style="border: none; font-size: 14px;"><strong>Claimed/Returned:</strong></td>
                <td style="border: none; font-size: 14px;">' . $count_claimed . '</td>
            </tr>
        </table>
    </div>

    <h3>Detailed Items List</h3>';

if ($count_items > 0) {
    $html .= '
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Description</th>
                <th>Type</th>
                <th>Date Lost</th>
                <th>Status</th>
                <th>Posted By</th>
                <th>Claimed By</th>
                <th>Claim Date</th>
            </tr>
        </thead>
        <tbody>';
    
    foreach ($items as $item) {
        $html .= '<tr>
            <td>' . (int)$item['id'] . '</td>
            <td>' . htmlspecialchars($item['description']) . '</td>
            <td>' . htmlspecialchars($item['item_type']) . '</td>
            <td>' . htmlspecialchars($item['date_lost'] ?? '—') . '</td>
            <td>' . htmlspecialchars(ucfirst($item['status'])) . '</td>
            <td>' . htmlspecialchars($item['posted_by_name'] ?? '—') . '</td>
            <td>' . htmlspecialchars($item['claimer_name'] ?? '—') . '</td>
            <td>' . htmlspecialchars($item['claim_date'] ?? '—') . '</td>
        </tr>';
    }
    
    $html .= '
        </tbody>
    </table>';
} else {
    $html .= '<p style="text-align: center; padding: 20px; background: #f9f9f9;">No items found matching the selected criteria.</p>';
}

$html .= '
    <div class="footer">
        <p>This is a system-generated report from TIP Lost & Found System</p>
        <p>For inquiries, please contact the administrator</p>
    </div>
</body>
</html>';

$options = new Options();
$options->set('isHtml5ParserEnabled', true);
$options->set('isRemoteEnabled', true);
$options->set('defaultFont', 'Arial');

$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();

$filename = 'Lost_Found_Report_' . date('Y-m-d_His') . '.pdf';

$dompdf->stream($filename, array('Attachment' => true));
exit;